vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
tasks:
  - name: Start Astro
    before: bash .devcontainer/install-bun.sh
    command: |
      export PATH="$HOME/.bun/bin:$PATH"
      ./start.sh
ports:
  - name: Astro Dev Server
    description: The development server
    port: 4321
    onOpen: open-browser
